QUICK_HELP = 'Enter `@jarvis help` for help on using the jarvis.'

HELP_MESSAGE = ('Jarvis usage:\n'
                '`@jarvis movies popularshows`\n'
                'Displays top trending shows\n'
                '`@jarvis movies popularmovies`\n'
                'Displays top trending movies\n'
                '`@jarvis movies search <movie-name>`\n'
                'Find movies matching the given movie-name\n\n'
                '`@jarvis weather <city-name>`\n'
                '`Displays and forecasts weather conditions`\n\n'
                '`@jarvis lyrics <composer-name> <song-name>`\n'
                '`Provides lyrics of the song queried`\n\n'
                '`@jarvis man <command-name>`\n'
                '`Provides man page for given command`\n\n'
                '`@jarvis ssh <username> <server-IP> <password> <command-name>`\n'
                '`Runs given command over SSH in network`\n\n'
                '`@jarvis sps start`\n'
                '`Starts the stone paper scissor game`\n'
                '`@jarvis sps <stone/paper/scissor>`\n'
                '`User can select either stone paper or scissor`\n\n'
                '`@jarvis hangman start`\n'
                '`Starts the hangman game`\n'
                '`@jarvis hangman <character>`\n'
                '`Unviels the character if it is present in the string`\n\n'
                '`@jarvis mind-game start`\n'
                '`Starts the mind-game`\n'
                '`@jarvis mind-game <x-coordinate> <y-coordinate>`\n'
                '`Unviels tile at position x and y (Zero indexed)`\n\n'
                '`@jarvis scrabble start`\n'
                '`Starts the scrabble game`\n'
                '`@jarvis scrabble <x-coordinate> <y-coordinate> <character>`\n'
                '`Places character at positon x y`\n\n'
                '`@jarvis todo start`\n'
                '`Initializes todo list`\n'
                '`@jarvis todo add <activity>`\n'
                '`Adds activity to todo list`\n'
                '`@jarvis todo remove <activity-id>`\n'
                '`Removes activity from todo list`\n'
                '`@jarvis todo list`\n'
                '`Displays todo list`\n\n'
                '`@jarvis currency <from-currency> <to-currency>`\n'
                '`Tells one from-currency is how much in second currency`\n\n'
                '`@jarvis calculator <expression>`\n'
                '`Performs arithmetic calculations`\n\n'
                '`@jarvis news <keyword>`\n'
                '`Displays latest news related to keywords`\n\n'
                '`@jarvis dictionary <word>`\n'
                '`Displays meaning of word`\n\n'
                '`@jarvis cricket`\n'
                '`Displays scores of latest cricket matches`\n\n'
                'Usage examples:\n'
                '* `@jarvis man cat`\n'
                '* `@jarvis ssh mohit 192.168.0.3 ********* ls -l`\n'
                '* `@jarvis hangman start`\n'
                '* `@jarvis weather lucknow`\n')
