QUICK_HELP = 'Enter `@Jarvis help` for help on using the jarvis.'

HELP_MESSAGE = ('Jarvis usage:\n'
                '`@Jarvis movies popularshows`\n'
                'Displays top trending shows\n'
                '`@Jarvis movies popularmovies`\n'
                'Displays top trending movies\n'
                '`@Jarvis movies search <movie-name>`\n'
                'Find movies matching the given movie-name\n\n'
                '`@Jarvis weather <city-name>`\n'
                '`Displays and forecasts weather conditions`\n\n'
                '`@Jarvis lyrics <composer-name> <song-name>`\n'
                '`Provides lyrics of the song queried`\n\n'
                '`@Jarvis man <command-name>`\n'
                '`Provides man page for given command`\n\n'
                '`@Jarvis ssh <username> <server-IP> <password> <command-name>`\n'
                '`Runs given command over SSH in network`\n\n'
                '`@Jarvis sps start`\n'
                '`Starts the stone paper scissor game`\n'
                '`@Jarvis sps <stone/paper/scissor>`\n'
                '`User can select either stone paper or scissor`\n\n'
                '`@Jarvis hangman start`\n'
                '`Starts the hangman game`\n'
                '`@Jarvis hangman <character>`\n'
                '`Unviels the character if it is present in the string`\n\n'
                '`@Jarvis mind-game start`\n'
                '`Starts the mind-game`\n'
                '`@Jarvis mind-game <x-coordinate> <y-coordinate>`\n'
                '`Unviels tile at position x and y (Zero indexed)`\n\n'
                '`@Jarvis scrabble start`\n'
                '`Starts the scrabble game`\n'
                '`@Jarvis scrabble <x-coordinate> <y-coordinate> <character>`\n'
                '`Places character at positon x y`\n\n'
                '`@Jarvis todo start`\n'
                '`Initializes todo list`\n'
                '`@Jarvis todo add <activity>`\n'
                '`Adds activity to todo list`\n'
                '`@Jarvis todo remove <activity-id>`\n'
                '`Removes activity from todo list`\n'
                '`@Jarvis todo list`\n'
                '`Displays todo list`\n\n'
                '`@Jarvis currency <from-currency> <to-currency>`\n'
                '`Tells one from-currency is how much in second currency`\n\n'
                '`@Jarvis calculator <expression>`\n'
                '`Performs arithmetic calculations`\n\n'
                '`@Jarvis news <keyword>`\n'
                '`Displays latest news related to keywords`\n\n'
                '`@Jarvis dictionary <word>`\n'
                '`Displays meaning of word`\n\n'
                '`@Jarvis cricket`\n'
                '`Displays scores of latest cricket matches`\n\n'
                'Usage examples:\n'
                '* `@Jarvis man cat`\n'
                '* `@Jarvis ssh mohit 192.168.0.3 ********* ls -l`\n'
                '* `@Jarvis hangman start`\n'
                '* `@Jarvis weather lucknow`\n')
